module.exports = {
	"lagou": {
		"adWord": Number,
		"companyFullName": String,
		"companyId": Number,
		"positionName": String,
		"workYear": String,
		"education": String,
		"jobNature": String,
		"positionId": Number, // 职位ID
		"createTime": String,
		"companyShortName": String,
		"score": Number,
		"city": String,
		"salary-min": Number,
		"salary-max": Number,
		"approve": Number,
		"positionAdvantage": String,
		"companyLogo": String,
		"industryField": String,
		"financeStage": String,
		"companyLabelList": Array,
		"district": String,
		"companySize": String,
		"imState": String,
		"businessZones": Array,
		"lastLogin": Number,
		"publisherId": Number,
		"explain": String,
		"plus": String,
		"pcShow": Number,
		"appShow": Number,
		"deliver": Number,
		"gradeDescription": String,
		"promotionScoreExplain": String,
		"firstType": String,
		"secondType": String,
		"positionLables": Array,
		"formatCreateTime": String
	}
};
